/**
 * Types and interfaces for the Know It All Wall feature
 * Standalone Q&A mode for rapid-fire question answering
 */

/**
 * Single answer option with keywords for voice-activated selection
 */
export interface AnswerWithKeywords {
  /** Heading summarizing the approach (e.g., "Technical Deep Dive", "Business Value Focus") */
  heading: string;

  /** One-sentence brief answer */
  brief: string;

  /** Bullet points expanding on the answer */
  bullets: string[];

  /** Full paragraph explanation */
  full: string;

  /** Two keywords required to confirm this answer (both must be spoken) */
  keywords: [string, string];
}

/**
 * Question card status lifecycle
 */
export type QuestionStatus =
  | 'generating'   // AI is generating answers
  | 'ready'        // Answers ready, waiting for keyword confirmation
  | 'confirming'   // First keyword detected, waiting for second
  | 'answered'     // Both keywords detected, answer confirmed
  | 'error';       // Failed to generate answers

/**
 * Individual question card in the Know It All Wall
 */
export interface QuestionCard {
  /** Unique identifier */
  id: string;

  /** The question text detected from speech */
  question: string;

  /** When the question was detected */
  timestamp: Date;

  /** Two answer options generated by AI */
  answers: {
    answer1: AnswerWithKeywords;
    answer2: AnswerWithKeywords;
  };

  /** Which answer was selected (1 or 2), undefined if none selected yet */
  selectedAnswer?: 1 | 2;

  /** Keywords detected so far (for confirmation tracking) */
  keywordsDetected: string[];

  /** Current status of this question */
  status: QuestionStatus;

  /** Error message if status is 'error' */
  errorMessage?: string;

  /** Whether this card is currently visible in the viewport */
  isVisible: boolean;

  /** Trigger word to activate this question (longest word in the question) */
  triggerWord?: string;

  /** Whether this question is currently active/being answered */
  isActive?: boolean;
}

/**
 * Export format for answered questions
 */
export interface ExportData {
  /** Export timestamp */
  exportedAt: Date;

  /** Total questions asked */
  totalQuestions: number;

  /** Questions that were answered (keyword confirmed) */
  answeredQuestions: Array<{
    question: string;
    timestamp: Date;
    selectedAnswer: 1 | 2;
    answer: {
      heading: string;
      brief: string;
      bullets: string[];
      full: string;
    };
  }>;
}
